name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.0'
      - name: Install Dependencies
        run: pip install -r ./backend/requirements.txt
      - name: Run Tests
        working-directory: ./backend
        env:
          SECRET_KEY: 'secret'
          ALLOWED_HOSTS: 'localhost'
        run: pytest
